
version: "1"

services:
  db:
    container_name: "postgres-16.1"
    image: postgres:alpine3.19
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
